custom_sales_territory_management/force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

custom_sales_territory_management/force-app/main/default/objects/Territory__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The standard owner field. The sales rep assigned to this territory.</description>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

custom_sales_territory_management/force-app/main/default/objects/Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The standard name field. Each record will be named after its specific zip code.</description>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

custom_sales_territory_management/force-app/main/default/classes/TestFactory/TestFactory.cls
public class TestFactory
{
    public static final String CRON_EXP_EVERYDAY_AT_MIDNIGHT = '0 0 0 * * ?';
    public static final String OWNER_USERNAME_TEST_1 = 'testuser1@sunmotors.com';
    public static final String OWNER_USERNAME_TEST_2 = 'testuser2@sunmotors.com';
    public static final String ZIP_CODE_DEALER_TEST_1 = '91001';
    public static final String ZIP_CODE_DEALER_TEST_2 = '91002';
    
    // Insertion of two users, two territories and one dealer account
    public static void insertTerritoryManagementData()
    {
        insert new User(
            FirstName = 'Test', 
            LastName = 'User 1',
            Email = 'testuser1@gmail.com',
            Username = OWNER_USERNAME_TEST_1,
            Alias = 'user1',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = 
            [
                SELECT Id 
                FROM Profile 
                WHERE Name = 'Standard User'
            ].Id
        );

        insert new User(
            FirstName = 'Test', 
            LastName = 'User 2',
            Email = 'testuser2@gmail.com',
            Username = OWNER_USERNAME_TEST_2,
            Alias = 'user2',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = 
            [
                SELECT Id 
                FROM Profile 
                WHERE Name = 'System Administrator'
            ].Id
        );

        Id OwnerId1Test = 
        [
            SELECT Id 
            FROM User 
            WHERE Username = :OWNER_USERNAME_TEST_1
        ].Id;

        insert new Territory__c(
            Name = 'Territory test 1', 
            Zip_Code__c = ZIP_CODE_DEALER_TEST_1, 
            Owner__c = OwnerId1Test
        ); 
        
        Id OwnerId2Test = 
        [
            SELECT Id 
            FROM User 
            WHERE Username = :OWNER_USERNAME_TEST_2
        ].Id;

        insert new Territory__c(
            Name = 'Territory test 2', 
            Zip_Code__c = ZIP_CODE_DEALER_TEST_2, 
            Owner__c = OwnerId2Test
        );

        insert new Account(
            Name = 'Dealer test 1', 
            BillingPostalCode = ZIP_CODE_DEALER_TEST_1, 
            OwnerId = OwnerId1Test
        );
    }
}